"""persist compacted conversation memory"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "2f1465dc7863"
down_revision = "46ba1f6a7865"
branch_labels = None
depends_on = None


def upgrade():
    """Apply the generated schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chats",
        sa.Column("context_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    """Reverse the generated schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chats", "context_summary")
    # ### end Alembic commands ###
