"""persist processing diagnostics"""

import sqlalchemy as sa
from alembic import op

revision = "4642d4fae103"
down_revision = "d18c6a20b5e9"
branch_labels = None
depends_on = None


def upgrade():
    """Apply the generated schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_stage_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("attempt_id", sa.String(length=36), nullable=False),
        sa.Column("stage", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["job_attempts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_job_stage_runs_attempt_id"), "job_stage_runs", ["attempt_id"], unique=False
    )
    op.add_column("job_attempts", sa.Column("error_code", sa.String(), nullable=True))
    op.add_column("job_attempts", sa.Column("error_retryable", sa.Boolean(), nullable=True))
    op.add_column("jobs", sa.Column("error_code", sa.String(), nullable=True))
    op.add_column("jobs", sa.Column("error_retryable", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    """Reverse the generated schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "error_retryable")
    op.drop_column("jobs", "error_code")
    op.drop_column("job_attempts", "error_retryable")
    op.drop_column("job_attempts", "error_code")
    op.drop_index(op.f("ix_job_stage_runs_attempt_id"), table_name="job_stage_runs")
    op.drop_table("job_stage_runs")
    # ### end Alembic commands ###
