"""add document overview discovery and agent traces"""

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "46ba1f6a7865"
down_revision = "b91f270f1115"
branch_labels = None
depends_on = None


def upgrade():
    """Apply the generated schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DO $$\nDECLARE installed_version text;\nBEGIN\n    SELECT extversion INTO installed_version FROM pg_extension WHERE extname = 'vector';\n    IF installed_version IS NULL OR\n       string_to_array(installed_version, '.')::int[] < ARRAY[0, 8, 0] THEN\n        RAISE EXCEPTION 'Document retrieval requires pgvector >=0.8.0 (installed: %)',\n            coalesce(installed_version, 'not installed');\n    END IF;\nEND $$;\n"
    )
    op.create_table(
        "document_overviews",
        sa.Column("version_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("generation_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("embedding_model", sa.String(length=128), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.Column(
            "search",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english'::regconfig, text)", persisted=True),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["version_id"], ["document_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("version_id"),
    )
    op.create_index(
        "ix_document_overviews_embedding_hnsw",
        "document_overviews",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": 32, "ef_construction": 200},
    )
    op.create_index(
        "ix_document_overviews_search",
        "document_overviews",
        ["search"],
        unique=False,
        postgresql_using="gin",
    )
    op.add_column(
        "messages",
        sa.Column(
            "agent_trace",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.execute(
        "CREATE TRIGGER workspace_change_insert_delete AFTER INSERT OR DELETE ON document_overviews FOR EACH ROW EXECUTE FUNCTION record_workspace_change()"
    )
    op.execute(
        "CREATE TRIGGER workspace_change_update AFTER UPDATE ON document_overviews FOR EACH ROW WHEN (OLD IS DISTINCT FROM NEW) EXECUTE FUNCTION record_workspace_change()"
    )
    # ### end Alembic commands ###


def downgrade():
    """Reverse the generated schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER workspace_change_update ON document_overviews")
    op.execute("DROP TRIGGER workspace_change_insert_delete ON document_overviews")
    op.drop_column("messages", "agent_trace")
    op.drop_index(
        "ix_document_overviews_search", table_name="document_overviews", postgresql_using="gin"
    )
    op.drop_index(
        "ix_document_overviews_embedding_hnsw",
        table_name="document_overviews",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": 32, "ef_construction": 200},
    )
    op.drop_table("document_overviews")
    # ### end Alembic commands ###
