"""persist committed workspace revisions"""

import sqlalchemy as sa
from alembic import op

revision = "b91f270f1115"
down_revision = "4642d4fae103"
branch_labels = None
depends_on = None


def upgrade():
    """Apply the generated schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspace_revisions",
        sa.Column("transaction_id", sa.BigInteger(), nullable=False),
        sa.Column("epoch", sa.String(length=36), nullable=True),
        sa.CheckConstraint(
            "(transaction_id = 0) = (epoch IS NOT NULL)", name="workspace_revision_epoch"
        ),
        sa.PrimaryKeyConstraint("transaction_id"),
    )
    op.execute(
        "INSERT INTO workspace_revisions (transaction_id, epoch) VALUES (0, gen_random_uuid()::text)"
    )
    op.execute(
        "CREATE FUNCTION record_workspace_change() RETURNS trigger\nLANGUAGE plpgsql AS $$\nBEGIN\n    EXECUTE format('INSERT INTO %I.workspace_revisions (transaction_id) VALUES ($1) ON CONFLICT (transaction_id) DO NOTHING', TG_TABLE_SCHEMA)\n        USING txid_current();\n    RETURN NULL;\nEND $$;"
    )
    op.execute(
        "CREATE TRIGGER workspace_change_insert_delete AFTER INSERT OR DELETE ON documents FOR EACH ROW EXECUTE FUNCTION record_workspace_change()"
    )
    op.execute(
        "CREATE TRIGGER workspace_change_update AFTER UPDATE ON documents FOR EACH ROW WHEN (OLD IS DISTINCT FROM NEW) EXECUTE FUNCTION record_workspace_change()"
    )
    op.execute(
        "CREATE TRIGGER workspace_change_insert_delete AFTER INSERT OR DELETE ON document_versions FOR EACH ROW EXECUTE FUNCTION record_workspace_change()"
    )
    op.execute(
        "CREATE TRIGGER workspace_change_update AFTER UPDATE ON document_versions FOR EACH ROW WHEN (OLD IS DISTINCT FROM NEW) EXECUTE FUNCTION record_workspace_change()"
    )
    op.execute(
        "CREATE TRIGGER workspace_change_insert_delete AFTER INSERT OR DELETE ON chats FOR EACH ROW EXECUTE FUNCTION record_workspace_change()"
    )
    op.execute(
        "CREATE TRIGGER workspace_change_update AFTER UPDATE ON chats FOR EACH ROW WHEN (OLD IS DISTINCT FROM NEW) EXECUTE FUNCTION record_workspace_change()"
    )
    op.execute(
        "CREATE TRIGGER workspace_change_insert_delete AFTER INSERT OR DELETE ON messages FOR EACH ROW EXECUTE FUNCTION record_workspace_change()"
    )
    op.execute(
        "CREATE TRIGGER workspace_change_update AFTER UPDATE ON messages FOR EACH ROW WHEN (OLD IS DISTINCT FROM NEW) EXECUTE FUNCTION record_workspace_change()"
    )
    op.execute(
        "CREATE TRIGGER workspace_change_insert_delete AFTER INSERT OR DELETE ON artifacts FOR EACH ROW EXECUTE FUNCTION record_workspace_change()"
    )
    op.execute(
        "CREATE TRIGGER workspace_change_update AFTER UPDATE ON artifacts FOR EACH ROW WHEN (OLD IS DISTINCT FROM NEW) EXECUTE FUNCTION record_workspace_change()"
    )
    op.execute(
        "CREATE TRIGGER workspace_change_insert_delete AFTER INSERT OR DELETE ON llm_calls FOR EACH ROW EXECUTE FUNCTION record_workspace_change()"
    )
    op.execute(
        "CREATE TRIGGER workspace_change_update AFTER UPDATE ON llm_calls FOR EACH ROW WHEN (OLD IS DISTINCT FROM NEW) EXECUTE FUNCTION record_workspace_change()"
    )
    op.execute(
        "CREATE TRIGGER workspace_change_insert_delete AFTER INSERT OR DELETE ON jobs FOR EACH ROW EXECUTE FUNCTION record_workspace_change()"
    )
    op.execute(
        "CREATE TRIGGER workspace_change_update AFTER UPDATE OF status, stage, attempts, error, error_code, next_at, started_at, finished_at ON jobs FOR EACH ROW WHEN (OLD IS DISTINCT FROM NEW) EXECUTE FUNCTION record_workspace_change()"
    )
    # ### end Alembic commands ###


def downgrade():
    """Reverse the generated schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER workspace_change_insert_delete ON documents")
    op.execute("DROP TRIGGER workspace_change_update ON documents")
    op.execute("DROP TRIGGER workspace_change_insert_delete ON document_versions")
    op.execute("DROP TRIGGER workspace_change_update ON document_versions")
    op.execute("DROP TRIGGER workspace_change_insert_delete ON chats")
    op.execute("DROP TRIGGER workspace_change_update ON chats")
    op.execute("DROP TRIGGER workspace_change_insert_delete ON messages")
    op.execute("DROP TRIGGER workspace_change_update ON messages")
    op.execute("DROP TRIGGER workspace_change_insert_delete ON artifacts")
    op.execute("DROP TRIGGER workspace_change_update ON artifacts")
    op.execute("DROP TRIGGER workspace_change_insert_delete ON llm_calls")
    op.execute("DROP TRIGGER workspace_change_update ON llm_calls")
    op.execute("DROP TRIGGER workspace_change_insert_delete ON jobs")
    op.execute("DROP TRIGGER workspace_change_update ON jobs")
    op.execute("DROP FUNCTION record_workspace_change()")
    op.drop_table("workspace_revisions")
    # ### end Alembic commands ###
