"""add hnsw and rename llm calls"""

from alembic import op

revision = "d18c6a20b5e9"
down_revision = "5a286abcc976"
branch_labels = None
depends_on = None


def upgrade():
    """Apply the generated schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DO $$\nDECLARE installed_version text;\nBEGIN\n    SELECT extversion INTO installed_version FROM pg_extension WHERE extname = 'vector';\n    IF installed_version IS NULL OR\n       string_to_array(installed_version, '.')::int[] < ARRAY[0, 8, 0] THEN\n        RAISE EXCEPTION 'Document retrieval requires pgvector >=0.8.0 (installed: %)',\n            coalesce(installed_version, 'not installed');\n    END IF;\nEND $$;\n"
    )
    op.rename_table("ai_calls", "llm_calls")
    op.execute('ALTER INDEX "ix_ai_calls_resource_id" RENAME TO "ix_llm_calls_resource_id"')
    op.execute('ALTER TABLE "llm_calls" RENAME CONSTRAINT "ai_calls_pkey" TO "llm_calls_pkey"')
    op.create_index(
        "ix_chunks_embedding_hnsw",
        "chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": 32, "ef_construction": 200},
    )
    # ### end Alembic commands ###


def downgrade():
    """Reverse the generated schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("llm_calls", "ai_calls")
    op.execute('ALTER INDEX "ix_llm_calls_resource_id" RENAME TO "ix_ai_calls_resource_id"')
    op.execute('ALTER TABLE "ai_calls" RENAME CONSTRAINT "llm_calls_pkey" TO "ai_calls_pkey"')
    op.drop_index(
        "ix_chunks_embedding_hnsw",
        table_name="chunks",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": 32, "ef_construction": 200},
    )
    # ### end Alembic commands ###
